### ISSUE TITLE
post注入参数怎么填写？

### ISSUE THREAD

**Issue by 609496288** [3xp10it/bypass_waf#1]
get请求是这样：python3 xwaf.py "http://127.0.0.1/1.php?id=1"
那么post请求怎么填写？

**Comment by 3xp10it** [comment]
这个暂时不支持,准备年后更新支持所有sqlmap参数。

**Comment by 3xp10it** [comment]
所有参数写法与sqlmap一样,现已更新支持所有sqlmap参数。
