### ISSUE TITLE
最新版Readline安装gcc编译报错，通过下面语句可手动更新

### ISSUE THREAD

**Issue by XTpeeps** [3xp10it/bypass_waf#13]
下载了最新的xwaf，运行发现安装readline报错，如下
![image](https://user-images.githubusercontent.com/9640837/35427495-b27c5a40-02a4-11e8-8649-78053d3b0001.png)

通过下面的方法解决了：https://stackoverflow.com/questions/22971681/installing-readline-module-in-python3
```
sudo apt-get install libncurses5-dev
sudo pip3 install readline
```
![image](https://user-images.githubusercontent.com/9640837/35427560-1eae3e04-02a5-11e8-8465-c04766f2fc3d.png)

note:
之前尝试下面的方法均无用
```
apt install  build-essential autoconf libtool pkg-config python-opengl python-imaging python-pyrex python-pyside.qtopengl idle-python2.7 qt4-dev-tools qt4-designer libqtgui4 libqtcore4 libqt4-xml libqt4-test libqt4-script libqt4-network libqt4-dbus python-qt4 python-qt4-gl libgle3 python-dev libssl-dev
sudo apt-get install libpq-dev python-dev libxml2-dev libxslt1-dev libldap2-dev libsasl2-dev libffi-dev
 1197  apt-get install libxml2-dev libxslt1-dev
apt-get install python3.6-dev
```

**Comment by lzskyline** [comment]
有效, 谢谢~

**Comment by 3xp10it** [comment]
新版本exp10it模块支持自动安装`apt-get install python3.6-dev`

**Comment by XTpeeps** [comment]
多谢，收到~  日后会及时反馈。
