### ISSUE TITLE
经常报这个错，然后无法继续向下执行

### ISSUE THREAD

**Issue by x7art** [3xp10it/bypass_waf#15]
Traceback (most recent call last):
  File "xwaf.py", line 2841, in <module>
    Program()
  File "xwaf.py", line 33, in __init__
    self.selfUpdate()
  File "xwaf.py", line 176, in selfUpdate
    latestVersion=getVersion("/tmp/xwaf.py")
  File "xwaf.py", line 171, in getVersion
    latestVersion=re.search(r"self\.currentVersion\s*=\s*(.*)",content).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

请问有微信或者QQ吗    加一下，，方便联系

**Comment by 3xp10it** [comment]
这个应该是网络问题导致没有成功下载xwaf.py到/tmp目录下，后来问题还存在吗？

**Comment by xiaoluanzzz** [comment]
我也遇到了同样的问题，重启网络，多次尝试后似乎也无法解决，有没有其他建议呢？

**Comment by 3xp10it** [comment]
运行的操作系统是什么？用的python版本是什么？

**Comment by xiaoluanzzz** [comment]
已经发送给你了，如果我找到解决方法，也会发布在这里，多谢

**Comment by 3xp10it** [comment]
我这边试了下那个url对应的运行情况,是正常的,你试试直接在你的环境下通过bash运行下面的命令,看看有没有异常:
`wget https://raw.githubusercontent.com/3xp10it/bypass_waf/master/xwaf.py -O /tmp/xwaf.py -q`

**Comment by xueqi-hk** [comment]
我终于弄清楚怎么回事了，我解决了，手动下载https://raw.githubusercontent.com/3xp10it/bypass_waf/master/xwaf.py的文件到本机，一定保证不是0字节，然后放入/tmp/目录下，给一个chmod 755 权限

重点来了：将所有xwaf.py文件 “注释掉177行!” 内容如下：“#os.system("wget https://raw.githubusercontent.com/3xp10it/bypass_waf/master/xwaf.py -O /tmp/xwaf.py -q")”
!!!删除掉这一行或者加 #号注释了，/tmp/xwaf.py 要删掉这一句，你运行的xwaf。py也要删掉这一句。
对，你自己观察。每次运行xwaf时，它都会自动去下载这个文件并覆盖已有的，但由于大陆长城防火墙，你会下载一个0字节的xwaf。py 在你的/tmp/目录里， 造成你运行时报错。

**Comment by 281066586** [comment]
楼主nb
