### ISSUE TITLE
运行 x.waf 显示网络连接不可达

### ISSUE THREAD

**Issue by lgf01010** [3xp10it/bypass_waf#16]
您好，每次运行时候 都要花费时间运行一段Requirement already up-to-date: exp10it in /usr/local/lib/python3.6/dist-packages
Requirement already up-to-date: bs4 in /usr/local/lib/python3.6/dist-packages (from exp10it)
Requirement already up-to-date: chardet in /usr/lib/python3/dist-packages (from exp10it)
Requirement already up-to-date: colorama in /usr/local/lib/python3.6/dist-packages (from exp10it)这样的代码，不知道是何原因，望解答

**Comment by 3xp10it** [comment]
这个是正常的，用于每次运行时自动更新exp10it模块（exp10it有时更新比较频繁）
