### ISSUE TITLE
forward parameters to sqlmap  ? 

### ISSUE THREAD

**Issue by gupthapowa** [3xp10it/bypass_waf#2]
Hello,

is the application able to pass parameters to sqlmap ( like --cookie )  )

also is it possible to force the number of parameters ( for exemples  when the request is not accepted because  2 parameters are expected)

**Comment by 3xp10it** [comment]
Not support for now,I will make it support all sqlmap parameters recently:D

**Comment by 3xp10it** [comment]
Support all kinds of sqlmap params now,and the usage is the same to sqlmap,I will close this issues.
