### ISSUE TITLE
kail&ubuntu均无法运行

### ISSUE THREAD

**Issue by 609496288** [3xp10it/bypass_waf#3]
下载的版本是2017-02-13
ubuntu提示：
![z1](https://cloud.githubusercontent.com/assets/20203054/23030203/09f8c468-f4a8-11e6-9128-190c2f1265e6.png)
kail2.0提示：
![z2](https://cloud.githubusercontent.com/assets/20203054/23030494/eece5b7a-f4a8-11e6-936b-7bcf466f755c.png)

请问如何解决？

**Comment by 3xp10it** [comment]
感谢issue,已修复,请下载最新版本
