### ISSUE TITLE
还是运行报错了

### ISSUE THREAD

**Issue by 609496288** [3xp10it/bypass_waf#4]
![a1](https://cloud.githubusercontent.com/assets/20203054/23269184/ac6ee1d2-fa2a-11e6-9a23-68c3fca1bf87.png)

版本是：[2017-02-23]

**Comment by 3xp10it** [comment]
试试这个https://www.reddit.com/r/learnpython/comments/24zwo4/340_ubuntu_1404_importerror_with_curses/里面的libncursesw5-dev (or possibly libncurses5-dev）
