### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by Tren** [3xp10it/bypass_waf#6]
python3 xwaf.py -u "http://xxxxxxxxxxxxxxx.com//article/lists?catid=xxx" -p catid
出现：
['sqlmap', '-u', 'http://xxxxxxxxxxxxxxx.com//article/lists?catid=xxx', '--batch', '-v', '3', '--threads', '4', '--random-agent', '--safe-url', 'http://xxxxxxxxx.com', '--safe-freq', '1', '--level', '3', '--smart']
['-u', 'http://xxxxxxxxxxxxxxx.com//article/lists?catid=xxx', '-p', 'catid']
[正在执行:sqlmap -u "http://xxxxxxxxxxxxxxx.com//article/lists?catid=xxx" -p "catid" --batch -v "3" --threads "4" --random-agent --safe-url "http://xxxxxxxxxxxxxxxx2sh: 1: sqlmap: not found-level "3" --smart]
touch: cannot touch '/root/.sqlmap/output/xxxxxxxxx.com/config_file.ini': No such file or directory
Traceback (most recent call last):
  File "xwaf.py", line 2810, in <module>
    Program()
  File "xwaf.py", line 96, in __init__
    update_config_file_key_value(self.log_config_file, 'default', 'finished_command_list', [])
  File "/usr/local/lib/python3.5/dist-packages/exp10it.py", line 2140, in update_config_file_key_value
    with open(file, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.sqlmap/output/xxxxxxxxx.com/config_file.ini'

**Comment by 3xp10it** [comment]
uname -a的结果是什么呢?

**Comment by Tren** [comment]
Linux iZaynmm6eeezk8Z 4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by 3xp10it** [comment]
是不是没有将sqlmap加入到path中?

**Comment by Tren** [comment]
应该是没有设置在path中的问题，我用kali测试了一下 成功了

**Comment by 3xp10it** [comment]
新版本已支持自动将sqlmap添加到$PATH
